server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # This is CRITICAL for React/Vite SPAs. If a user refreshes on a sub-route,
        # Nginx tries to find a physical file. This tells Nginx to fallback to index.html
        # and let React Router handle the URL.
        try_files $uri $uri/ /index.html;
    }
}
